### ISSUE TITLE
Arquitetura e interface de serviço

### ISSUE THREAD

**Issue by campiolo** [JVZavatin/ProjetoSD2022#1]
1. Desenhar a arquitetura do sistema, explicando os componentes, como se relacionam, software e tecnologias usadas.
2. Especificar a(s) interface(s) de serviço.
3. Disponibilizar no README.md

**Comment by campiolo** [comment]
Não esquecer de atualizar o git com a arquitetura e interface de serviço.

**Comment by JVZavatin** [comment]
Resolvida no dia 10/11/2022
